story_homepage:
    path:     /
    defaults: { _controller: StoryBundle:Default:index }
ajout:
    path:     /ajouter
    defaults: { _controller: StoryBundle:stories:create}
aff:
    path:     /afficher
    defaults: { _controller: StoryBundle:stories:read}
supp:
    path:     /supprimer/{idstorie}
    defaults: { _controller: StoryBundle:stories:delete}

modif:
    path:     /update/{idstorie}
    defaults: { _controller: StoryBundle:stories:modifier}



recherche:
    path:     /re
    defaults: { _controller: StoryBundle:stories:recherche}

