story_homepage:
    path:     /
    defaults: { _controller: StoryBundle:Default:index }
creat:
    path:     /ajouter
    defaults: { _controller: StoryBundle:stories:create}
read:
    path:     /afficher
    defaults: { _controller: StoryBundle:stories:read}
delete:
    path:     /supprimer/{idstorie}
    defaults: { _controller: StoryBundle:stories:delete}

modifier:
    path:     /update/{idstorie}
    defaults: { _controller: StoryBundle:stories:modifier}



recherche:
    path:     /re
    defaults: { _controller: StoryBundle:stories:recherche}

