story_homepage:
    path:     /
    defaults: { _controller: StoryBundle:Default:index }

creation:
    path:     /ajout
    defaults: { _controller: StoryBundle:stories:create}


afficher:
    path:     /afficher
    defaults: { _controller: StoryBundle:stories:read}

Supp:
    path:     /supprimer/{idstorie}
    defaults: { _controller: StoryBundle:stories:delete}




modif:
    path:     /modif/{idstorie}
    defaults: { _controller: StoryBundle:stories:modifier}



recherche:
    path:     /re
    defaults: { _controller: StoryBundle:stories:recherche}

