user_homepage:
    path:     /index
    defaults: { _controller: UserBundle:Default:index }
inscri:
    path:     /inscri
    defaults: { _controller: UserBundle:front:signUp }


quiz:
    path:     /ajoutQuiz
    defaults: { _controller: UserBundle:quiz:ajouterQuiz }

packChoix:
        path:     /packChoix
        defaults: { _controller: UserBundle:pack:packChoix }

packChoix_pays:
        path:     /packChoix_pays
        defaults: { _controller: UserBundle:pack:packChoixPays }

AjouterMesPack:
        path:     /AjouterMesPack/{idPack}
        defaults: { _controller: UserBundle:pack:ajouterMesPack }